-- Review accounts for App Store / Google Play
-- Password: Test1234!
--
-- Preferred: run from terminal (creates Auth + profiles automatically):
--   SUPABASE_URL=https://mgyufoyornzbwvgdfojb.supabase.co \
--   SUPABASE_SERVICE_ROLE_KEY=<service role> \
--   npm run review:users
--
-- Manual fallback: Dashboard → Authentication → Users → Add user, then:

-- INSERT INTO public.profiles (id, email, name, city, role, status, organization_id)
-- SELECT
--   '<auth-user-uuid>',
--   'tourist@test.tourgo.app',
--   'Review Tourist',
--   'Алматы',
--   'TOURIST',
--   'active',
--   NULL
-- WHERE NOT EXISTS (SELECT 1 FROM public.profiles WHERE email = 'tourist@test.tourgo.app');
