/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForOperatorsRouteImport } from './routes/for-operators'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TourTourIdRouteImport } from './routes/tour.$tourId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOperatorsRoute = ForOperatorsRouteImport.update({
  id: '/for-operators',
  path: '/for-operators',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTourIdRoute = TourTourIdRouteImport.update({
  id: '/tour/$tourId',
  path: '/tour/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-operators': typeof ForOperatorsRoute
  '/search': typeof SearchRoute
  '/tour/$tourId': typeof TourTourIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-operators': typeof ForOperatorsRoute
  '/search': typeof SearchRoute
  '/tour/$tourId': typeof TourTourIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-operators': typeof ForOperatorsRoute
  '/search': typeof SearchRoute
  '/tour/$tourId': typeof TourTourIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/for-operators' | '/search' | '/tour/$tourId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/for-operators' | '/search' | '/tour/$tourId'
  id: '__root__' | '/' | '/for-operators' | '/search' | '/tour/$tourId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForOperatorsRoute: typeof ForOperatorsRoute
  SearchRoute: typeof SearchRoute
  TourTourIdRoute: typeof TourTourIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-operators': {
      id: '/for-operators'
      path: '/for-operators'
      fullPath: '/for-operators'
      preLoaderRoute: typeof ForOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$tourId': {
      id: '/tour/$tourId'
      path: '/tour/$tourId'
      fullPath: '/tour/$tourId'
      preLoaderRoute: typeof TourTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForOperatorsRoute: ForOperatorsRoute,
  SearchRoute: SearchRoute,
  TourTourIdRoute: TourTourIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
